### PR TITLE
add credit

### PR DESCRIPTION
**Pull request by npdoty**
@juliocaizan @ysmartin can you confirm that this appropriately updates our credits page?

suggested by @p4pnl, thanks Michael

### CODE REVIEW

**Comment by juliocaizan** [comment]
Hi Nick, 

As I have two affiliations, could you add me in a new line please?

Julio C. Caiza [Escuela Politécnica Nacional] (http://www.epn.edu.ec) and [Universidad Politécnica de Madrid] (http://www.upm.es)

Best Regards

**Comment by npdoty** [comment]
@juliocaizan can you check this revision?

**Comment by juliocaizan** [comment]
It is perfect @npdoty . Thanks :)

**Comment by juliocaizan** [comment]
Hi again @npdoty, 
I don't know if I am wrong but I still don't see the 'about page' updated (https://privacypatterns.org/about/). Could you check it please?

**Pull request merged**
