### PR TITLE
render with pattern standardization in patterns#9

### PR DESCRIPTION
**Pull request by mohit**
rendered from addition of https://github.com/privacypatterns/patterns/pull/9 and https://github.com/privacypatterns/patterns/pull/11 

Visible at https://next.privacypatterns.org

There are a few issues still to fix here before pushing this to the main site. Examples:

1. Name of the pattern appears twice on the top of the page 

2. In cases where previous headings were removed (in patterns#9) and converted to numbered lists in (patterns#11), they are not properly formatted 

3. In many cases in https://github.com/privacypatterns/patterns/pull/9  categories in the metadata do not match the Categories section at the end.

### CODE REVIEW

**Comment by mohit** [comment]
I'll be working on this over the next couple of days to fix the rendering issues.

**Comment by p4pnl** [comment]
At present the hyde field categories is broader than the schema field, perhaps we can drop the schema field since it already exists in hyde. Same argument for name/title.

As for the numbered lists issue, ~~it seems the auto-generation creates a new list each time~~. It turns out we just need to intent content under each list item to show markdown it's related. E.g. 

Markdown | Preview
------------|----------
capture | capture

CSS is still something that can be done after markdown as well, how about changing h2 font-size to 28pt and the ul list-style-type to circle (if the indent doesn't fix that automatically)?

**Comment by p4pnl** [comment]
See https://github.com/privacypatterns/patterns/pull/12 for this fix applied

**Comment by npdoty** [comment]
My only additional concern (beyond the formatting issues that @mohit noted) was that the categories as a separate section at the bottom seemed confusing since we already had those tags in metadata and rendered at the top. With pull#13, that seems resolved as well, so, looks good to me.

**Comment by mohit** [comment]
re-rendered with the changes. There are still some minor formatting issues but this looks better and is a step in the right direction. I'm going to close this up, and create an issue/email out some thoughts on how to deal with non-standard headers in patterns.

**Pull request merged**
