### PR TITLE
Fixed filenames for use on case-insensitive file systems.

### PR DESCRIPTION
**Pull request by squell**
The repository was causing trouble when cloned on Windows; presumably some of the files were renamed at some point but older versions were kept; I removed all of the files I think were outdated (but have not done any careful checking)

### CODE REVIEW

**Comment by squell** [comment]
The problem is that there were different files whose filenames only differed in the case; so e.g., there is a file
`site/content/patterns/sticky-policy.html`
and
`site/content/patterns/Sticky-policy.html`

Which wreaks havoc when working with this repository on systems which are not case-sensitive (e.g. anything on Windows)

**Comment by squell** [comment]
Note that this issue was introduced in #93.

**Comment by p4pnl** [comment]
Patterns in this repo have been both sentence case, title case, and lower case, all of which are ambiguous to Windows if there are mutliple variations. All lower case is the least common of these (only two, both obsolete), which this PR removes because the other versions are more recent. We have almost as many title case as sentence case.

As for category names, all lower case is instead the most common. So removing those which are capitalized duplicates (only four, also obsolete) was faster.

This leaves a straightforward, minimal effort rule we can enforce: _that categories are all lowercase, and patterns should all be sentence case._

Note that all of the removed files in this PR are obsolete. They are unrelated to a counterpart in ``privacypatterns/patterns``, they were autogenerated at some point and never removed. In ``privacypatterns/patterns``, there are no patterns in lowercase, and no categories which are capitalized.

**Comment by npdoty** [comment]
I have been trying for some time to accept this PR, resolve the conflicts and merge it. However, the filename case sensitivity issues are making my local system very confused: when I force checkout the files on squell's branch, they have different cases than when I look at them on github.

**Comment by npdoty** [comment]
I think this is fixed in 5c89873be0fb653957bf7efd841dad347ca87df8 but I could never get GitHub to see that this opened PR should be merged (because it couldn't actually see any differences between this PR and the existing tree). Anyway, if the issue is resolved for others now, I suggest that we just close this PR.

**Pull request merged**
