### PR TITLE
Render Pattern Relations (Outdated)

### PR DESCRIPTION
**Pull request by p4pnl**
@mohit @npdoty This PR builds off of #99 and #98.

It uses the RaphaelJS library to render patterns above the category and post pages and show their relations. This looks as follows.

tactic

And when hovering:

indivdualpattern

Patterns can be dragged and the relationship connections will stay connected. They can be clicked and will navigate to the appropriate page. On individual pattern pages, relationship shorthands (com, use, etc.) are also shown when hovering. If the pattern in question is hovered over, all shorthands are shown. 

To do this we add ``raphael`` and ``graffle.js``, and modify the following:
- [`_category.html`](https://github.com/p4pnl/privacypatterns/compare/collapsiblecats...p4pnl:renderrelations#diff-dd8b84f0ff05a4c3bf6db3f24fe821a8): We add the JS using block `extra_css`, which allows us to add to the head of pages during the Hyde generation. In this we loop through posts (patterns) in the category and add them to a list (`inputData`). We include their URL, their categories, and a dictionary of their relationships, split by spaces. A pattern's `hyde` block can then use for e.g. `com: Some-Pattern-Name Some-Other-Pattern`. This would happen in [the other repo](https://github.com/privacypatterns/patterns). Category colors are also added to a dictionary. These are retrieved from `settings.py`. A div is added to hold the patterns.
- [`_post.html`](https://github.com/p4pnl/privacypatterns/compare/collapsiblecats...p4pnl:renderrelations#diff-fa038260b9ed6d2792c941b383ab8feb): The same was done for individual pattern pages. Instead we only have one pattern and its related patterns. Each related pattern's category also needs a loop to be retrieved. 
- [``main.css``](https://github.com/p4pnl/privacypatterns/compare/collapsiblecats...p4pnl:renderrelations#diff-d043f4a65e37ac3be0e933ebf6f5df41): a few lines of CSS are added for the holder Div.
- [``settings.py``](https://github.com/p4pnl/privacypatterns/compare/collapsiblecats...p4pnl:renderrelations#diff-404df50edb361b9c1eb9bf311c4fbd5e): each tactic in meta now has an assigned color (the same as for the categories list).
- `[some patterns].md`: (not this PR) To take advantage of this PR, we can add relationships to pattern Hyde blocks. The change works without it though. The attached images use my local changes to `privacypatterns/patterns`.

I will add some further description of [`graffle.js`](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js) tomorrow.

The most populated category is shown below (you can see which one's aren't pure control by their color):
strategy

### CODE REVIEW

**Comment by mohit** [comment]
I've deployed this branch to https://next.privacypatterns.org but like you mentioned we also need to make changes to the [patterns repo](https://github.com/privacypatterns/patterns). Do you want to make a PR there too?

**Comment by HecticSeptic** [comment]
It seems to be working on [next.privacypatterns.org](next.privacypatterns.org):
image
From #98:
image

We do indeed still need to populate patterns with their relationships, but these changes work without in the mean time. We should also still modify 'Miscellaneous' to 'Tags' in a follow-up PR as @npdoty suggested.

**Comment by HecticSeptic** [comment]
Some additional information on [``graffle.js``](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js) and [`rafael`](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/raphael). 

[RaphaelJS](http://dmitrybaranovskiy.github.io/raphael/) is a cross-browser javascript library for rendering SVG. Using this, on [page load](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L12), we create a [`paper`](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L85) in a `div` named 'holder'. We set up a few things here, such as functions for onhover/drag/mouseup and the populating of our pattern collection. 

Patterns come from Hyde's page generation, where we add an `inputData` variable. [Using this](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L92), we [add each pattern](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L223) as a `texts` list item. This adds text to the `paper` and let's us keep access to it. We also store its color, which we later apply to its [associated shape](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L253). To access them by name, `patternsDict` stores each text according to the same format as relationships in hyde blocks. That is, filename without an extension. This allows us to set a relationship [`connection`](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L559) later.

[After the initial setup](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L101), we loop through the given relationships (this is different for categories and individual pattern pages). An individual pattern page always has `inputData.length == 1`, and should add related patterns as their own `texts` items. Once the patterns are all added, [we loop again](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L124) to add relationships (which need all patterns to exist first). This adds a `connection` for each, showing them along with the relationship name ([on hover](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L302)) for individual patterns. Categories only show the lines ([on hover](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L44)) as otherwise would be too cluttered at that level. The [loop the follows](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L163) is not used (see [1]), as we don't add any `relations` items.

Next we [add shapes and events to the `texts` items](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L188). Text is not a very flexible element in Raphael, so we place each above a `rect`, and always move them together. The connections connect to the text, but are behind the `rect`. The shapes use the color of the last (first in reverse) tactic given by the pattern's hyde block. At first this was lightened with [`hexmult`](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L255), but fortunately the colors we already have are light enough. Colors come from the second hyde generated variable: `catColors`.

Finally we make sure the patterns can be [placed](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L381) without overlapping each other. We first sort them by width, (which we also got the max of, along with `maxHeight` in the [previous loop](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L192)). Then we call [the same function](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L220) we use on [resize](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L365).

We make sure that `holder` and thus `paper` are no larger than necessary. Every time we cannot [fit the next pattern in](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L425) the given space, we add a column. For all the columns we have, we try to [put](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L465) the next pattern in [the most empty one](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L436). If the pattern is too large to fit even a full row, we [make it smaller](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L429).

[1] We don't use [relationship circles](https://github.com/p4pnl/privacypatterns/blob/7d7abfe30a9694ca6622aa0a0586da809bc2e4b4/site/media/js/raphael/graffle.js#L163) at the moment, but it could be preferable to show relationship types in places they don't overlap other shapes.

**Comment by HecticSeptic** [comment]
@mohit could you update [next.privacypatterns.org](next.privacypatterns.org) with 5af8b25 and privacypatterns/patterns#28?

**Pull request closed without merging**
