### PR TITLE
pull contributed categories and patterns

### PR DESCRIPTION
**Pull request by mohit**
from https://github.com/privacypatterns/patterns/pull/3

### CODE REVIEW

**Comment by mohit** [comment]
Since this is a huge PR, I published this branch to https://next.privacypatterns.org/ for all to look at as we review. 

One thing I've been thinking of - most  categories only have one pattern under them. Maybe we need to spend some time to standardize the categorization of existing patterns into fewer buckets to ease navigation. 

cc: @hkopp @p4pnl

**Comment by npdoty** [comment]
Thanks, @mohit. This looks good to me, and similar to how I rendered it while reviewing the content import step.

Sometime soon we're going to need better pagination or use of categories for browsing all the patterns here: https://next.privacypatterns.org/patterns/
I don't think it's absolutely necessary for this import, but it may be by the next one.

**Comment by hkopp** [comment]
I agree. Originally they were tags as well as categories (the design strategies of Hoepman). Now I made them all to categories, since I think that may be easier for a practitioner to find the pattern which is relevant for him.

**Comment by mohit** [comment]
now live at https://privacypatterns.org/

**Pull request merged**
